#mysql配置
spring:
   datasource: 
      url: jdbc:mysql://localhost:13306/test?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: kp0808KP
      driver-class-name: com.mysql.cj.jdbc.Driver
#服务配置
server:
   port: 8082


